name: Test Action
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      max-parallel: 24
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3

      - name: run test suite
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run test
